_MAKE_SWS_(x, 0)
_MAKE_SWS_(y, 1)
_MAKE_SWS_(z, 2)
_MAKE_SWS_(w, 3)
_MAKE_SWS_(xy, 0, 1)
_MAKE_SWS_(yx, 1, 0)
_MAKE_SWS_(yz, 1, 2)
_MAKE_SWS_(zw, 2, 3)
_MAKE_SWS_(wz, 3, 2)
_MAKE_SWS_(xyz, 0, 1, 2)
_MAKE_SWS_(yzw, 1, 2, 3)
_MAKE_SWS_(zyx, 2, 1, 0)
_MAKE_SWS_(wxyz, 3, 0, 1, 2)
_MAKE_SWS_(zwxy, 2, 3, 0, 1)
_MAKE_SWS_(wzyx, 3, 2, 1, 0)
